### ISSUE TITLE
Missing the 'puppetversion' fact

### ISSUE THREAD

**Issue by rji** [mcanevet/rspec-puppet-facts#11]
I'm not sure if this is intended or not, but this gem seems to be missing the `puppetversion` fact, which has been around since at least [Facter 1.6](https://docs.puppetlabs.com/facter/1.6/core_facts.html#puppetversion).

I'm currently using the following workaround:

```ruby
let(:facts) do
  facts.merge!({ :puppetversion => ENV['PUPPET_VERSION'] || '3.7.0' })
end
```

**Comment by mcanevet** [comment]
@rji this is intentional as it depends on the puppet version you are using. I use this as a wrokaround:

```ruby
let(:facts) do
  facts.merge({ :puppetversion => Puppet.version })
end
```
