### ISSUE TITLE
Memoizing facts

### ISSUE THREAD

**Issue by ekohl** [mcanevet/rspec-puppet-facts#114]
Currently `on_supported_os` collects facts on every invocation. Typically it's called in every file with the same arguments (none). These calls can be slow and the result will be the same anyway. In https://github.com/voxpupuli/voxpupuli-test/commit/5fb4475db7ec25ce39bd9e4fbd667045a96b4006 I implemented memoization for voxpupuli-test.

Would this be a welcome addition to rspec-puppet-facts itself or should we keep it in voxpupuli-test?

**Comment by mcanevet** [comment]
@ekohl this could be a good improvement.

**Comment by tuxmea** [comment]
Question is: where to add?
From my point of view this should be directly in rspec-puppet-facts.
I know some people nut using this with pdk or voxpupuli-tests but as a single gem.

**Comment by ekohl** [comment]
I've opened #122. It still has some failures but right now I don't have time to look into it. Should be a good start though.
