### ISSUE TITLE
Allow adding a global fact in spec_helper.rb

### ISSUE THREAD

**Issue by ekohl** [mcanevet/rspec-puppet-facts#14]
In case your module needs a fact to be present (say ```concat_basedir```), it would greatly simplify life if you could add in globally from ```spec_helper.rb```.

**Comment by igalic** [comment]
@ekohl this should probably go into @camptocamp / facterdb…

**Comment by mcanevet** [comment]
I'm not sure this should be done in facterdb

**Comment by ekohl** [comment]
@mcanevet I'm thinking that you want some sort of hooking mechanism to change facts. Some sort of post_load hook that would be a more generalized version of https://github.com/mcanevet/rspec-puppet-facts/blob/138facc65050a9043fca2d5a30223dd7fabca40c/lib/rspec-puppet-facts.rb#L44-L52.

**Comment by phathocker** [comment]
:+1:
