### ISSUE TITLE
v1.4.0 breaks if mcollective isn't installed

### ISSUE THREAD

**Issue by jerith** [mcanevet/rspec-puppet-facts#25]
See https://travis-ci.org/praekeltfoundation/puppet-gluster/jobs/106945015 for an example of this.

**Comment by mcanevet** [comment]
@jerith we are working on this, we'll publish v1.4.1 that fixes the issue soon

**Comment by mcanevet** [comment]
@jerith v1.4.1 released

**Comment by jerith** [comment]
Excellent, thanks. :-)
