### ISSUE TITLE
Remove Ruby 1.8.7/1.9.3 support

### ISSUE THREAD

**Issue by rnelson0** [mcanevet/rspec-puppet-facts#44]
If you look at the [latest builds](https://travis-ci.org/mcanevet/rspec-puppet-facts/jobs/173396544), ruby 1.8.7 tests are in the allowed_failures group already and now 1.9.3 tests are failing (see #43). You could probably fix this for 1.9.3, somehow, but it's only a stop-gap solution as more and more gems start giving up 1.9 support. I would recommend removing both version entirely, as they provide no benefit due to failing during gem downloads, and only result in slower test completion.

The [required_ruby_version](http://guides.rubygems.org/specification-reference/#required_ruby_version) should be set in the gemspec at this time as well.

**Comment by ghoneycutt** [comment]
Removed!
