### ISSUE TITLE
Support the facts/trusted hashes

### ISSUE THREAD

**Issue by rnelson0** [mcanevet/rspec-puppet-facts#47]
There is no normalization within rspec-puppet between legacy and the equivalent structured facts hash. e.g. `$operatingsystemmajrelease` and `$facts['os']['release']['major']`, thought they contain the same value. Are there any plans to provide those facts in `rspec-puppet-facts`?

/cc @rodjek

**Comment by mcanevet** [comment]
@rnelson0 I'm not sure to understand. If I look at https://github.com/camptocamp/facterdb/blob/master/facts/3.3/debian-8-x86_64.facts I can see both `operatingsystemmajrelease` and `os.release.major` facts.

**Comment by bastelfreak** [comment]
@mcanevet they are present in the facterdb, but I wasn't able to use any structured hash in our test, only the legacy facts. Do we need to do something special to activate them?

We always do:

```ruby
on_supported_os.each do |os, facts|
  context "on #{os} " do
    let :facts do
      facts
    end
```

**Comment by domcleal** [comment]
This works fine for me on at least one module where both are used. Do you have a (non-)working example?

**Comment by rnelson0** [comment]
/me slinks off in shame after realizing this is the one rspec test that wasn't converted to use rspec-puppet-facts :(

Sorry, all. I'll leave this open for a repro of @bastelfreak but otherwise I'll go ahead and close it.

**Comment by bastelfreak** [comment]
good morning. I doublechecked my code and noticed that I used rspec-puppet-facts wrong. Works fine!
