### ISSUE TITLE
operatingsystemrelease filter should work with string instead of array

### ISSUE THREAD

**Issue by ckaenzig** [mcanevet/rspec-puppet-facts#6]
If I want to create a test block using `on_supported_os` with only one os release, I still have to make the filter an array instead of a single string which I would expect to work, as other filters like `operatingsystem` work with a string.

Example that doesn't work:

```
on_supported_os({
  :supported_os => [ {
    'operatingsystem' => 'RedHat',
    'operatingsystemrelease' => '5',
  } ]
}).each do ...
```

Example that actually works:

```
on_supported_os({
  :supported_os => [ {
    'operatingsystem' => 'RedHat',
    'operatingsystemrelease' => ['5'],
  } ]
}).each do ...
```

**Comment by mcanevet** [comment]
@ckaenzig I suppose using `Array(os_sup['operatingsystemrelease'])` here https://github.com/mcanevet/rspec-puppet-facts/blob/master/lib/rspec-puppet-facts.rb#L14 would do the trick.
