### ISSUE TITLE
Question: why is mcollective-client a dependency?

### ISSUE THREAD

**Issue by logicminds** [mcanevet/rspec-puppet-facts#60]
Just curious why the mcollective client is required.

**Comment by DavidS** [comment]
The dependency was added in https://github.com/mcanevet/rspec-puppet-facts/pull/26, but without explanation. @mcanevet any ideas?

**Comment by mcanevet** [comment]
I don't remember why...

**Comment by DavidS** [comment]
Ah, it's used in `common_facts` to inject the `MCollective::VERSION`.

**Comment by DavidS** [comment]
@logicminds does that answer your question? -> https://github.com/mcanevet/rspec-puppet-facts/blob/fe21de12108fbab0123bdc4db2365a29ea62f171/lib/rspec-puppet-facts.rb#L207

**Comment by logicminds** [comment]
wow, a whole dependency just to grab a version number.  Could you not just statically define it?

**Comment by mcanevet** [comment]
There is no way to statically define it as it depends on the version installed.
