### ISSUE TITLE
Strict fact retrieval

### ISSUE THREAD

**Issue by jovrum** [mcanevet/rspec-puppet-facts#63]
Supported OS entries in metadata.json which don't match any facts are simply silently not tested. This could happen when the user has a typo in the OS name or in any of the OS release names, or if FacterDB has not yet been populated with facts for the given OS name and release.

For example, given a semantically correct support matrix like so:

```json
"operatingsystem_support": [
   {
        "operatingsystem": "CentOS",
        "operatingsystemrelease": ["6", "7"]
    }
]
```

`on_supported_os` could have 0, 1 or 2 entries depending on Facter version and FacterDB parity. Thus with the recommended use pattern for `on_supported_os`, it's possible that no testing occurs at all, or less testing is happening than intended, with at most a warning message in the test result output.

With typos in the support matrix, this problem could happen even with a fully populated FacterDB.

I think rspec-puppet-facts should throw an error if facts for a given OS name and release are not found. I'm guessing this precludes the use of `FacterDB.get_facts`, the API of which seems to be the root cause of this issue (or maybe validating its return value is an acceptable solution).

**Comment by DavidS** [comment]
Set the environment variable `SPEC_FACTS_STRICT` to `yes` to avoid this behaviour. See the bottom of https://github.com/mcanevet/rspec-puppet-facts#running-your-tests for documentation.

**Comment by jovrum** [comment]
@DavidS, thanks! I missed that, will try it out.

**Comment by jovrum** [comment]
Well, `SPEC_FACTS_STRICT` only seems to cover one case: when Facter has been updated and FacterDB hasn't been populated with the new facts yet. It will still happily accept OS specifications without any facts.

I also don't think the non-strict behavior is a good default. When is that useful? Who would want their test suite to pass when potentially no tests are actually performed?

**Comment by DavidS** [comment]
I thought SPEC_FACTS_STRICT triggers every time an entry in operatingsystem_support is not matched to a facterdb source?

Re non-default: when implementing this there was a strong request from other users to not make this the default.
