### ISSUE TITLE
Cut a new release to support windows server 2016

### ISSUE THREAD

**Issue by TraGicCode** [mcanevet/rspec-puppet-facts#65]
Can @rodjek or @mcanevet please cut a new release of this module rubygems.  I ran into a bug where windows server 2016 facts don't get pulled back which is resolved in master.

**Comment by logicminds** [comment]
+1

**Comment by luceo** [comment]
+1

**Comment by mcanevet** [comment]
Can someone prepare a PR for the `CHANGELOG`? I don't have time to review changes since `v1.8.0` but I can do the release afterwards.

**Comment by logicminds** [comment]
I can prepare the changelog.  Should I also bump the version in gemspec?

**Comment by mcanevet** [comment]
@logicminds no I'll do it. Thanks
