### ISSUE TITLE
facterversion filter fails with windows and facter version 3.x

### ISSUE THREAD

**Issue by logicminds** [mcanevet/rspec-puppet-facts#66]
The hardwaremodule fact changed between facter versions 2.x and 3.x.  This is causing a failure to lookup windows systems in FacterDB when the facterversion is set to the 3.x version.

Facterversion 3.x (hardwaremodel => 'x86_64')
https://github.com/camptocamp/facterdb/blob/master/facts/3.5/windows-2012%20r2-x86_64.facts#L21

Facterversion 2.x (hardwaremodel => '64')
https://github.com/camptocamp/facterdb/blob/master/facts/2.5/windows-2012%20r2-x86_64.facts#L7

https://github.com/mcanevet/rspec-puppet-facts/blob/master/lib/rspec-puppet-facts.rb#L64

Because we hardcode x64 regardless of facter versions failures to lookup will fail.

Additionally

`hardwaremodel = version =~ /^[12]\./ ? 'x64' : 'x86_64'`  is not tied to a windows release and should be bound to the facterversion instead of the windows version.  This causes another issue where windows 2012 systems with facterversion of 3.x would never be found either.

**Comment by TraGicCode** [comment]
I think this is resolved in master and a new release needs to be cut.  https://github.com/mcanevet/rspec-puppet-facts/issues/65

**Comment by logicminds** [comment]
ahh, yes going to close then.
