### ISSUE TITLE
AIX hardware model should not be x86_64

### ISSUE THREAD

**Issue by TJM** [mcanevet/rspec-puppet-facts#69]
I have been chatting on Puppet Community slack, asking about why my AIX tests aren't working (aren't running for AIX), and someone pointed me to https://github.com/mcanevet/rspec-puppet-facts/blob/010538181409b159c93e265a4648dd966ae77dfb/lib/rspec-puppet-facts.rb#L58-L66

This should have a case for AIX, but I am not sure what hardwaremodel needs to be set to. I was thinking  `powerpc` (uname -p) or `isa` fact based on what the other operating systems are using. However the "hardwaremodel" fact comes out as something like `IBM,8284-22A` which is pretty non-useful. It makes me think that either the hardwaremodel is hopelessly generic on other platforms or its incorrectly populated for AIX. Maybe we could just set the hardware model filter to something like `/^IBM/` ?

I figured I would start here with a discussion before trying to throw code at it, cause I am soo green when it comes to rspec testing that I am not really sure how to even test this code. :)

NOTE: I recently submitted [some facts](https://github.com/camptocamp/facterdb/commit/1a437a5279b55f7038926d3e05bd0ffbc228f9a2) for reference.

~tommy

**Comment by TJM** [comment]
FYI I also filed: https://tickets.puppetlabs.com/browse/FACT-1827

**Comment by rodjek** [comment]
Looks like this has been fixed up (or at least worked around) by #71. Feel free to reopen if that is not the case.
