### ISSUE TITLE
Inconsistent FQDNs in facts

### ISSUE THREAD

**Issue by domcleal** [mcanevet/rspec-puppet-facts#8]
It would be useful if the facts had consistent, known hostnames and domains.  This would make it easier to construct tests for manifests using these facts, without having to override/merge these.

**Comment by mcanevet** [comment]
@domcleal I already set hostname to `foo.example.com` here https://github.com/mcanevet/rspec-puppet-facts/blob/master/facts/Vagrantfile so `hostname`, `domain` and `fqdn` should be consistent...

If you don't like `foo.example.com` we just have to update the Vagrantfile and regenerate the facts.

**Comment by domcleal** [comment]
Oh apologies, my checkout was very much out of date.  Thanks!
